export const COINS = [
  { img: "src/assets/zora.svg", title: "Zora" },
  { img: "src/assets/ZetaChain.svg", title: "ZetaChain" },
  { img: "src/assets/arbitrum.svg", title: "Arbitrum" },
  { img: "src/assets/avalanche.svg", title: "Avalanche" },
  { img: "src/assets/base.svg", title: "Base" },
  { img: "src/assets/blast.svg", title: "Blast" },
  { img: "src/assets/bnb.svg", title: "Binance Smart Chain" },
  { img: "src/assets/celo.svg", title: "Celo" },
  { img: "src/assets/eth.svg", title: "Ethereum" },
  { img: "src/assets/gnosis.svg", title: "Gnosis" },
  { img: "src/assets/Ancient8.svg", title: "Ancient8" },
  { img: "src/assets/manta.svg", title: "Manta Pacific" },
  { img: "src/assets/moonbeam.svg", title: "Moonbeam" },
  { img: "src/assets/Optimism.svg", title: "OP Mainnet" },
  { img: "src/assets/polygon.svg", title: "Polygon zkEVM" },
  { img: "src/assets/Redstone.svg", title: "Redstone" },
  { img: "src/assets/Scroll.svg", title: "Scroll" },
  { img: "src/assets/Mode.svg", title: "Mode" },
  { img: "src/assets/Viction.svg", title: "Viction" },
  { img: "src/assets/zkSYNC.svg", title: "zkSYNC" },
];
