export const COINS = [
  { img: "zora.svg", title: "Zora" },
  { img: "ZetaChain.svg", title: "ZetaChain" },
  { img: "arbitrum.svg", title: "Arbitrum" },
  { img: "avalanche.svg", title: "Avalanche" },
  { img: "base.svg", title: "Base" },
  { img: "blast.svg", title: "Blast" },
  { img: "bnb.svg", title: "Binance Smart Chain" },
  { img: "celo.svg", title: "Celo" },
  { img: "eth.svg", title: "Ethereum" },
  { img: "gnosis.svg", title: "Gnosis" },
  { img: "Ancient8.svg", title: "Ancient8" },
  { img: "manta.svg", title: "Manta Pacific" },
  { img: "moonbeam.svg", title: "Moonbeam" },
  { img: "Optimism.svg", title: "OP Mainnet" },
  { img: "polygon.svg", title: "Polygon zkEVM" },
  { img: "Redstone.svg", title: "Redstone" },
  { img: "Scroll.svg", title: "Scroll" },
  { img: "Mode.svg", title: "Mode" },
  { img: "Viction.svg", title: "Viction" },
  { img: "zkSYNC.svg", title: "zkSYNC" },
];
