export const COINS = [
  { img: "arbitrum.svg", title: "Arbitrum", chainId: 42161 },
  // { img: "eth.svg", title: "Ethereum", chainId: 1 }, // не нужен пока что
  { img: "base.svg", title: "Base", chainId: 8453 },
  { img: "ZetaChain.svg", title: "ZetaChain", chainId: 7341 },
  { img: "avalanche.svg", title: "Avalanche", chainId: 43114 },
  { img: "bnb.svg", title: "Binance Smart Chain", chainId: 56 },
  { img: "celo.svg", title: "Celo", chainId: 42220 },
  { img: "gnosis.svg", title: "Gnosis", chainId: 100 },
  { img: "manta.svg", title: "Manta Pacific", chainId: 34434 },
  { img: "moonbeam.svg", title: "Moonbeam", chainId: 1284 },
  { img: "Optimism.svg", title: "OP Mainnet", chainId: 10 },
  { img: "polygon.svg", title: "Polygon zkEVM", chainId: 1101 },
  { img: "Scroll.svg", title: "Scroll", chainId: 534352 },
  // { img: "Redstone.svg", title: "Redstone", chainId: 1 },
  // { img: "Mode.svg", title: "Mode", chainId: 1 },
  // { img: "Viction.svg", title: "Viction", chainId: 1 },
  // { img: "zkSYNC.svg", title: "zkSYNC", chainId: 1 },
  // { img: "zora.svg", title: "Zora", chainId: 42161 },
  // { img: "blast.svg", title: "Blast", chainId: 1 },
  // { img: "Ancient8.svg", title: "Ancient8", chainId: 1 },
];
